# Generated by Django 2.2.12 on 2023-11-28 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='classroom',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='roll_no',
            field=models.ForeignKey(db_column='roll_no', on_delete=django.db.models.deletion.CASCADE, to='classroom.Student', to_field='roll_no'),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_no',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
