# Generated by Django 2.2.12 on 2023-11-26 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_auto_20231113_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='classmaterial',
            name='subject',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classmaterial',
            name='material',
            field=models.FileField(upload_to='materials'),
        ),
    ]
