# Generated by Django 2.2.12 on 2023-11-26 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_auto_20231126_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classnotice',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
