# Generated by Django 2.2.12 on 2023-11-26 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_auto_20231126_1659'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classnotice',
            unique_together={('teacher', 'message', 'id')},
        ),
    ]
