# Generated by Django 2.2.12 on 2023-11-08 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0007_auto_20231108_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagetoteacher',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='classroom.Student'),
        ),
        migrations.AlterField(
            model_name='messagetoteacher',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='classroom.Teacher'),
        ),
        migrations.AlterUniqueTogether(
            name='messagetoteacher',
            unique_together={('student', 'message')},
        ),
        migrations.CreateModel(
            name='MeetLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
                ('message_html', models.TextField(editable=False)),
                ('students', models.ManyToManyField(related_name='class_meet', to='classroom.Student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_meet', to='classroom.Teacher')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('teacher', 'message')},
            },
        ),
    ]
