# Generated by Django 2.2.12 on 2023-11-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0008_auto_20231108_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetlink',
            name='starting_time',
            field=models.DateTimeField(default=' '),
        ),
    ]
